language: go
go:
  - 1.6
  - tip
sudo: false
before_script:
  - go get ./...
  - go get github.com/bitly/go-simplejson
  - go get github.com/garyburd/redigo/redis
before_install:
  - cp .netrc ~
  - chmod 600 .netrc
script: npm run-script coveralls
install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

