language: go
go:
  - 1.6
  - tip
sudo: false
before_script:
  - go get ./...
  - go get github.com/bitly/go-simplejson
  - go get github.com/garyburd/redigo/redis

before_install:
  - cp .netrc ~
  - chmod 600 .netrc
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
#install:
#  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
#  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

script:
  - $HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN
