language: go
sudo: false
before_script:
  - go vet ./...
  - go get github.com/bitly/go-simplejson
install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

